### ISSUE TITLE
'No module named build'

### ISSUE THREAD

**Issue by DeeJay** [joan2937/picod#1]
Using RasPiOS Buster [32] on RPi2B

```
 $ git clone https://github.com/joan2937/picod.git
Cloning into 'picod'...
remote: Enumerating objects: 88, done.
remote: Counting objects: 100% (88/88), done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 88 (delta 39), reused 81 (delta 32), pack-reused 0
Unpacking objects: 100% (88/88), done.
 $ cd picod
 $ cd PYTHON
 $ python3 -m build
/usr/bin/python3: No module named build
 $

```

How/where should that 'build' module be installed as a prerequisite, please?

(Probably a basic Python infrastructure oversight of mine rather than anything directly wrong with picod.)

**Comment by joan2937** [comment]
See http://abyz.me.uk/picod/

http://abyz.me.uk/picod/download.html
```
The Python set up tools are needed during installation of the Python module.

These tools may be installed with the following command.

sudo apt install python-setuptools python3-setuptools

python2 -m pip install --upgrade build # only if you want to use Python2
python3 -m pip install --upgrade build
```

**Comment by DeeJay** [comment]
Ooops! Apologies... Started reading "To build the C pico daemon from source..." and skipped the rest of the Prerequisites paragraph!

So definitely my oversight - thank you for pointing that out politely.
